### ISSUE TITLE
Off Screen Windows should be Recovered by Restore All Windows

### ISSUE THREAD

**Issue by noah-dykoski** [smithscripts/mdi-desktop#1]
Feature Request: When windows are off screen (task bar buttons turn red), using Restore All Windows (alt-d) should recover the off screen windows.

**Comment by smithscripts** [comment]
Fixed: Off screen windows not being recovered by restore all window button

**Comment by noah-dykoski** [comment]
When the off screen window is the front window, it still hides first on Hide All Windows, before it is restored.  It should be treated as a minimized window immediately after it goes off screen.
